//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesPoint
    {
        public int Id { get; set; }
        public int TimeSeriesId { get; set; }
        public int PeriodId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal SPValue { get; set; }
    
        public virtual TimePeriod TimePeriod { get; set; }
        public virtual TimeSery TimeSery { get; set; }
    }
}
